/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent1 {
    }
    interface MyComponent2 {
    }
}
declare global {
    interface HTMLMyComponent1Element extends Components.MyComponent1, HTMLStencilElement {
    }
    var HTMLMyComponent1Element: {
        prototype: HTMLMyComponent1Element;
        new (): HTMLMyComponent1Element;
    };
    interface HTMLMyComponent2Element extends Components.MyComponent2, HTMLStencilElement {
    }
    var HTMLMyComponent2Element: {
        prototype: HTMLMyComponent2Element;
        new (): HTMLMyComponent2Element;
    };
    interface HTMLElementTagNameMap {
        "my-component-1": HTMLMyComponent1Element;
        "my-component-2": HTMLMyComponent2Element;
    }
}
declare namespace LocalJSX {
    interface MyComponent1 {
    }
    interface MyComponent2 {
    }
    interface IntrinsicElements {
        "my-component-1": MyComponent1;
        "my-component-2": MyComponent2;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component-1": LocalJSX.MyComponent1 & JSXBase.HTMLAttributes<HTMLMyComponent1Element>;
            "my-component-2": LocalJSX.MyComponent2 & JSXBase.HTMLAttributes<HTMLMyComponent2Element>;
        }
    }
}
